version: '2'
services:
    xutility-app:
        image: xutility
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://xutility-mysql:3306/xutility?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=xutility-elasticsearch:9300
        ports:
            - 8080:8080
    xutility-mysql:
        extends:
            file: mysql.yml
            service: xutility-mysql
    xutility-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: xutility-elasticsearch
